CREATE TABLE event_log(
    id SERIAL PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    GUILD_ID BIGINT NOT NULL REFERENCES guild(guild_id),
    SENDER_ID BIGINT,
    EMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)