name: Deploy to VPS

on:
  push:
    branches:
      - main
      - deploy-workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17' # или любая другая версия Java, необходимая для вашего приложения
          distribution: 'oracle'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --exclude-task test

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar # или любой другой путь, который содержит ваш собранный JAR-файл
          overwrite: true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APPLICATION_PATH }}
            rm -f *.jar # Удаление всех JAR-файлов из директории
            artifact_url=$(curl -sH "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${{ steps.artifact-upload-step.outputs.artifact-url }}" | jq -r '.artifacts[0].archive_download_url')
            wget $artifact_url
            mv *.jar ./captain-cocker-backend.jar
